const monstersList = [
    { id: 0, name: "Golem", rarity: "Common", img: "golem.gif" },
    { id: 1, name: "Horse", rarity: "Common", img: "horse.gif" },
    { id: 2, name: "Hyena", rarity: "Common", img: "hyena.gif" },
    { id: 3, name: "Crocodile", rarity: "Common", img: "crocodile.gif" },
    { id: 4, name: "Orc", rarity: "Common", img: "orc.gif" },
    { id: 5, name: "Polar Bear", rarity: "Common", img: "polar_bear.gif" },
    { id: 6, name: "Scarab", rarity: "Common", img: "scarab.gif" },
    { id: 7, name: "Scorpion", rarity: "Common", img: "scorpion.gif" },
    { id: 8, name: "Snake", rarity: "Common", img: "snake.gif" },
    { id: 9, name: "Spider", rarity: "Common", img: "spider.gif" },
    { id: 10, name: "Cyclops", rarity: "Common", img: "cyclops.gif" },
    { id: 11, name: "Demon Skeleton", rarity: "Common", img: "demon_skeleton.gif" },
    { id: 12, name: "Djinn", rarity: "Common", img: "djinn.gif" },
    { id: 13, name: "Bonelord", rarity: "Rare", img: "bonelord.gif" },
    { id: 14, name: "Electrify", rarity: "Rare", img: "electrify.gif" },
    { id: 15, name: "Fire Elemental", rarity: "Rare", img: "fire_elemental.gif" },
    { id: 16, name: "Medusa", rarity: "Rare", img: "medusa.gif" },
    { id: 17, name: "Minotaur", rarity: "Rare", img: "minotaur.gif" },
    { id: 18, name: "Skullcrusher", rarity: "Rare", img: "skullcrusher.gif" },
    { id: 19, name: "Dragon", rarity: "Rare", img: "dragon.gif" },
    { id: 20, name: "Snowman", rarity: "Epic", img: "snowman.gif" },
    { id: 21, name: "Hydra", rarity: "Epic", img: "hydra.gif" },
    { id: 22, name: "Unicorn", rarity: "Epic", img: "unicorn.gif" },
    { id: 23, name: "Demon", rarity: "Epic", img: "demon.gif" },
];

module.exports = { id: 0, monstersList };
